import { DevicePreset } from './types';

// Values sourced from public Apple/Google/Microsoft device spec sheets and
// developer references (Apple's published points/safe-area tables, Apple's
// iPhone 17 technical specifications pages, Android density-bucket math
// cross-checked against Google's confirmed Pixel 8 dp figure). insets
// approximate status bar / home indicator / notch safe areas. A few
// Pro-tier Pixel dp values are derived from confirmed physical-pixel counts
// via standard density-bucket math (dp = physical px / density factor)
// since Google doesn't publish exact dp figures for every model.
export const devicePresets: DevicePreset[] = [
  // --- iOS phones -----------------------------------------------------
  {
    id: 'iphone-se',
    name: 'iPhone SE',
    platform: 'ios',
    formFactor: 'phone',
    width: 375,
    height: 667,
    pixelRatio: 2,
    insets: { top: 20, bottom: 0, left: 0, right: 0 },
    notch: 'none',
    homeIndicator: 'physical-button',
  },
  {
    id: 'iphone-11',
    name: 'iPhone 11',
    platform: 'ios',
    formFactor: 'phone',
    width: 414,
    height: 896,
    pixelRatio: 2,
    insets: { top: 44, bottom: 34, left: 0, right: 0 },
    notch: 'notch',
    homeIndicator: 'swipe-bar',
  },
  {
    id: 'iphone-12-mini',
    name: 'iPhone 12 Mini',
    platform: 'ios',
    formFactor: 'phone',
    width: 375,
    height: 812,
    pixelRatio: 3,
    insets: { top: 50, bottom: 34, left: 0, right: 0 },
    notch: 'notch',
    homeIndicator: 'swipe-bar',
  },
  {
    id: 'iphone-12',
    name: 'iPhone 12',
    platform: 'ios',
    formFactor: 'phone',
    width: 390,
    height: 844,
    pixelRatio: 3,
    insets: { top: 47, bottom: 34, left: 0, right: 0 },
    notch: 'notch',
    homeIndicator: 'swipe-bar',
  },
  {
    id: 'iphone-12-pro-max',
    name: 'iPhone 12 Pro Max',
    platform: 'ios',
    formFactor: 'phone',
    width: 428,
    height: 926,
    pixelRatio: 3,
    insets: { top: 47, bottom: 34, left: 0, right: 0 },
    notch: 'notch',
    homeIndicator: 'swipe-bar',
  },
  {
    id: 'iphone-13-mini',
    name: 'iPhone 13 Mini',
    platform: 'ios',
    formFactor: 'phone',
    width: 375,
    height: 812,
    pixelRatio: 3,
    insets: { top: 47, bottom: 34, left: 0, right: 0 },
    notch: 'notch',
    notchVariant: 'narrow',
    homeIndicator: 'swipe-bar',
  },
  {
    id: 'iphone-13',
    name: 'iPhone 13',
    platform: 'ios',
    formFactor: 'phone',
    width: 390,
    height: 844,
    pixelRatio: 3,
    insets: { top: 47, bottom: 34, left: 0, right: 0 },
    notch: 'notch',
    notchVariant: 'narrow',
    homeIndicator: 'swipe-bar',
  },
  {
    id: 'iphone-13-pro-max',
    name: 'iPhone 13 Pro Max',
    platform: 'ios',
    formFactor: 'phone',
    width: 428,
    height: 926,
    pixelRatio: 3,
    insets: { top: 47, bottom: 34, left: 0, right: 0 },
    notch: 'notch',
    notchVariant: 'narrow',
    homeIndicator: 'swipe-bar',
  },
  {
    id: 'iphone-14',
    name: 'iPhone 14',
    platform: 'ios',
    formFactor: 'phone',
    width: 390,
    height: 844,
    pixelRatio: 3,
    insets: { top: 47, bottom: 34, left: 0, right: 0 },
    notch: 'notch',
    notchVariant: 'narrow',
    homeIndicator: 'swipe-bar',
  },
  {
    id: 'iphone-14-plus',
    name: 'iPhone 14 Plus',
    platform: 'ios',
    formFactor: 'phone',
    width: 428,
    height: 926,
    pixelRatio: 3,
    insets: { top: 47, bottom: 34, left: 0, right: 0 },
    notch: 'notch',
    notchVariant: 'narrow',
    homeIndicator: 'swipe-bar',
  },
  {
    id: 'iphone-14-pro',
    name: 'iPhone 14 Pro',
    platform: 'ios',
    formFactor: 'phone',
    width: 393,
    height: 852,
    pixelRatio: 3,
    insets: { top: 59, bottom: 34, left: 0, right: 0 },
    notch: 'dynamic-island',
    homeIndicator: 'swipe-bar',
  },
  {
    id: 'iphone-14-pro-max',
    name: 'iPhone 14 Pro Max',
    platform: 'ios',
    formFactor: 'phone',
    width: 430,
    height: 932,
    pixelRatio: 3,
    insets: { top: 59, bottom: 34, left: 0, right: 0 },
    notch: 'dynamic-island',
    homeIndicator: 'swipe-bar',
  },
  {
    id: 'iphone-15',
    name: 'iPhone 15',
    platform: 'ios',
    formFactor: 'phone',
    width: 393,
    height: 852,
    pixelRatio: 3,
    insets: { top: 59, bottom: 34, left: 0, right: 0 },
    notch: 'dynamic-island',
    homeIndicator: 'swipe-bar',
  },
  {
    id: 'iphone-15-plus',
    name: 'iPhone 15 Plus',
    platform: 'ios',
    formFactor: 'phone',
    width: 430,
    height: 932,
    pixelRatio: 3,
    insets: { top: 59, bottom: 34, left: 0, right: 0 },
    notch: 'dynamic-island',
    homeIndicator: 'swipe-bar',
  },
  {
    id: 'iphone-15-pro',
    name: 'iPhone 15 Pro',
    platform: 'ios',
    formFactor: 'phone',
    width: 393,
    height: 852,
    pixelRatio: 3,
    insets: { top: 59, bottom: 34, left: 0, right: 0 },
    notch: 'dynamic-island',
    homeIndicator: 'swipe-bar',
  },
  {
    id: 'iphone-15-pro-max',
    name: 'iPhone 15 Pro Max',
    platform: 'ios',
    formFactor: 'phone',
    width: 430,
    height: 932,
    pixelRatio: 3,
    insets: { top: 59, bottom: 34, left: 0, right: 0 },
    notch: 'dynamic-island',
    homeIndicator: 'swipe-bar',
  },
  {
    id: 'iphone-16',
    name: 'iPhone 16',
    platform: 'ios',
    formFactor: 'phone',
    width: 393,
    height: 852,
    pixelRatio: 3,
    insets: { top: 59, bottom: 34, left: 0, right: 0 },
    notch: 'dynamic-island',
    homeIndicator: 'swipe-bar',
  },
  {
    id: 'iphone-16-plus',
    name: 'iPhone 16 Plus',
    platform: 'ios',
    formFactor: 'phone',
    width: 430,
    height: 932,
    pixelRatio: 3,
    insets: { top: 59, bottom: 34, left: 0, right: 0 },
    notch: 'dynamic-island',
    homeIndicator: 'swipe-bar',
  },
  {
    id: 'iphone-16-pro',
    name: 'iPhone 16 Pro',
    platform: 'ios',
    formFactor: 'phone',
    width: 402,
    height: 874,
    pixelRatio: 3,
    insets: { top: 62, bottom: 34, left: 0, right: 0 },
    notch: 'dynamic-island',
    homeIndicator: 'swipe-bar',
  },
  {
    id: 'iphone-16-pro-max',
    name: 'iPhone 16 Pro Max',
    platform: 'ios',
    formFactor: 'phone',
    width: 440,
    height: 956,
    pixelRatio: 3,
    insets: { top: 62, bottom: 34, left: 0, right: 0 },
    notch: 'dynamic-island',
    homeIndicator: 'swipe-bar',
  },
  {
    id: 'iphone-17',
    name: 'iPhone 17',
    platform: 'ios',
    formFactor: 'phone',
    width: 390,
    height: 844,
    pixelRatio: 3,
    insets: { top: 59, bottom: 34, left: 0, right: 0 },
    notch: 'dynamic-island',
    homeIndicator: 'swipe-bar',
  },
  {
    id: 'iphone-17-pro',
    name: 'iPhone 17 Pro',
    platform: 'ios',
    formFactor: 'phone',
    width: 402,
    height: 874,
    pixelRatio: 3,
    insets: { top: 62, bottom: 34, left: 0, right: 0 },
    notch: 'dynamic-island',
    homeIndicator: 'swipe-bar',
  },
  {
    id: 'iphone-17-pro-max',
    name: 'iPhone 17 Pro Max',
    platform: 'ios',
    formFactor: 'phone',
    width: 440,
    height: 956,
    pixelRatio: 3,
    insets: { top: 62, bottom: 34, left: 0, right: 0 },
    notch: 'dynamic-island',
    homeIndicator: 'swipe-bar',
  },

  // --- iOS tablets ------------------------------------------------------
  {
    id: 'ipad-pro-11',
    name: 'iPad Pro 11"',
    platform: 'ios',
    formFactor: 'tablet',
    width: 834,
    height: 1194,
    pixelRatio: 2,
    insets: { top: 24, bottom: 20, left: 0, right: 0 },
    notch: 'none',
    homeIndicator: 'swipe-bar',
  },
  {
    id: 'ipad-9th-gen',
    name: 'iPad (9th gen)',
    platform: 'ios',
    formFactor: 'tablet',
    width: 810,
    height: 1080,
    pixelRatio: 2,
    insets: { top: 20, bottom: 20, left: 0, right: 0 },
    notch: 'none',
    homeIndicator: 'physical-button',
  },

  // --- Android phones -----------------------------------------------------
  {
    id: 'pixel-4a',
    name: 'Pixel 4a',
    platform: 'android',
    formFactor: 'phone',
    width: 393,
    height: 851,
    pixelRatio: 2.75,
    insets: { top: 24, bottom: 0, left: 0, right: 0 },
    notch: 'punch-hole',
    homeIndicator: 'gesture-pill',
  },
  {
    id: 'pixel-6',
    name: 'Pixel 6',
    platform: 'android',
    formFactor: 'phone',
    width: 412,
    height: 915,
    pixelRatio: 2.625,
    insets: { top: 32, bottom: 24, left: 0, right: 0 },
    notch: 'punch-hole',
    homeIndicator: 'gesture-pill',
  },
  {
    id: 'pixel-6-pro',
    name: 'Pixel 6 Pro',
    platform: 'android',
    formFactor: 'phone',
    width: 411,
    height: 891,
    pixelRatio: 3.5,
    insets: { top: 32, bottom: 24, left: 0, right: 0 },
    notch: 'punch-hole',
    homeIndicator: 'gesture-pill',
  },
  {
    id: 'pixel-7',
    name: 'Pixel 7',
    platform: 'android',
    formFactor: 'phone',
    width: 412,
    height: 915,
    pixelRatio: 2.625,
    insets: { top: 32, bottom: 24, left: 0, right: 0 },
    notch: 'punch-hole',
    homeIndicator: 'gesture-pill',
  },
  {
    id: 'pixel-7-pro',
    name: 'Pixel 7 Pro',
    platform: 'android',
    formFactor: 'phone',
    width: 411,
    height: 891,
    pixelRatio: 3.5,
    insets: { top: 32, bottom: 24, left: 0, right: 0 },
    notch: 'punch-hole',
    homeIndicator: 'gesture-pill',
  },
  {
    id: 'pixel-8',
    name: 'Pixel 8',
    platform: 'android',
    formFactor: 'phone',
    width: 404,
    height: 897,
    pixelRatio: 2.67,
    insets: { top: 32, bottom: 24, left: 0, right: 0 },
    notch: 'punch-hole',
    homeIndicator: 'gesture-pill',
  },
  {
    id: 'pixel-8-pro',
    name: 'Pixel 8 Pro',
    platform: 'android',
    formFactor: 'phone',
    width: 448,
    height: 997,
    pixelRatio: 3,
    insets: { top: 32, bottom: 24, left: 0, right: 0 },
    notch: 'punch-hole',
    homeIndicator: 'gesture-pill',
  },
  {
    id: 'pixel-9',
    name: 'Pixel 9',
    platform: 'android',
    formFactor: 'phone',
    width: 404,
    height: 906,
    pixelRatio: 2.67,
    insets: { top: 32, bottom: 24, left: 0, right: 0 },
    notch: 'punch-hole',
    homeIndicator: 'gesture-pill',
  },
  {
    id: 'pixel-9-pro',
    name: 'Pixel 9 Pro',
    platform: 'android',
    formFactor: 'phone',
    width: 427,
    height: 952,
    pixelRatio: 3,
    insets: { top: 32, bottom: 24, left: 0, right: 0 },
    notch: 'punch-hole',
    homeIndicator: 'gesture-pill',
  },
  {
    id: 'galaxy-s21',
    name: 'Galaxy S21',
    platform: 'android',
    formFactor: 'phone',
    width: 360,
    height: 800,
    pixelRatio: 3,
    insets: { top: 24, bottom: 0, left: 0, right: 0 },
    notch: 'punch-hole',
    homeIndicator: 'gesture-pill',
  },
  {
    id: 'oneplus-8-pro',
    name: 'OnePlus 8 Pro',
    platform: 'android',
    formFactor: 'phone',
    width: 360,
    height: 800,
    pixelRatio: 4,
    insets: { top: 24, bottom: 0, left: 0, right: 0 },
    notch: 'punch-hole',
    notchPosition: 'left',
    homeIndicator: 'gesture-pill',
  },
  {
    id: 'galaxy-note20-ultra',
    name: 'Samsung Galaxy Note 20 Ultra',
    platform: 'android',
    formFactor: 'phone',
    width: 412,
    height: 883,
    pixelRatio: 3.5,
    insets: { top: 32, bottom: 24, left: 0, right: 0 },
    notch: 'punch-hole',
    homeIndicator: 'gesture-pill',
  },

  // --- Android tablets ----------------------------------------------------
  {
    id: 'galaxy-tab-s8',
    name: 'Galaxy Tab S8',
    platform: 'android',
    formFactor: 'tablet',
    width: 800,
    height: 1280,
    pixelRatio: 2,
    insets: { top: 24, bottom: 0, left: 0, right: 0 },
    notch: 'punch-hole',
    homeIndicator: 'gesture-pill',
  },
  {
    id: 'android-tablet-medium',
    name: 'Android Tablet (Medium)',
    platform: 'android',
    formFactor: 'tablet',
    width: 1024,
    height: 1350,
    pixelRatio: 2,
    insets: { top: 24, bottom: 0, left: 0, right: 0 },
    notch: 'punch-hole',
    homeIndicator: 'gesture-pill',
  },
  {
    id: 'android-tablet-large',
    name: 'Android Tablet (Large)',
    platform: 'android',
    formFactor: 'tablet',
    width: 1280,
    height: 1880,
    pixelRatio: 2,
    insets: { top: 24, bottom: 0, left: 0, right: 0 },
    notch: 'punch-hole',
    homeIndicator: 'gesture-pill',
  },

  {
    id: 'custom',
    name: 'Custom',
    platform: 'custom',
    formFactor: 'phone',
    width: 400,
    height: 800,
    pixelRatio: 2,
    insets: { top: 0, bottom: 0, left: 0, right: 0 },
    notch: 'none',
    homeIndicator: 'none',
  },
];

export const defaultDevice = devicePresets[0];
